name: repomanager
description: "An application for manage your local git repos in a easy and intuitive way"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  file_picker: ^8.0.0
  sembast: ^3.8.2
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.5.2

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.21.0

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:

  uses-material-design: true
